# Site settings
title: CI and CD with GitHub
description: A demo blog
email: remko@github.com
twitter_username: aggenebbisj
github_username:  aggenebbisj
baseurl:
url: https://agg-ci-cd-workshop.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
